version: "3"
services:
  app:
    build: ./app
    volumes:
      - ./app:/var/www/html:z
    depends_on:
      - mysql
    ports:
      - "80:80"
    env_file:
      - ./.env
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - database-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=default
      - MYSQL_PASSWORD=default
      - MYSQL_ROOT_PASSWORD=default
      - MYSQL_DATABASE=default
volumes:
  database-volume: